// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGOB4rWorKSFtXf32MY-kv1ciMHsulq8',
    appId: '1:973124903276:web:de0b333c456c3712e2d349',
    messagingSenderId: '973124903276',
    projectId: 'kelas-5e0ff',
    authDomain: 'kelas-5e0ff.firebaseapp.com',
    databaseURL: 'https://kelas-5e0ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kelas-5e0ff.appspot.com',
    measurementId: 'G-LD7T6FR4GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFiw_b6pmtzrlDT7Kjdp2ovQJhbOZN7Y',
    appId: '1:973124903276:android:2ae3bdcf3e3a5a29e2d349',
    messagingSenderId: '973124903276',
    projectId: 'kelas-5e0ff',
    databaseURL: 'https://kelas-5e0ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kelas-5e0ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufePyyqPc3roS4vC3JWvYLr2hvomz3Vs',
    appId: '1:973124903276:ios:cb26808fa0350307e2d349',
    messagingSenderId: '973124903276',
    projectId: 'kelas-5e0ff',
    databaseURL: 'https://kelas-5e0ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kelas-5e0ff.appspot.com',
    iosBundleId: 'com.dimas.app',
  );
}
